### ISSUE TITLE
urlMiddle should not been encoded

### ISSUE THREAD

**Issue by simonbaudry** [gomoob/backbone.hateoas#11]
When urlMiddle parameter is set with URI special characters, they are encoded while they should not be.

**Comment by bgaillard** [comment]
Hi Simon, you're right their was a bug in the `Hal.Model.url()` method, the `urlMiddle` should not be encoded. 

This is now fixed with https://github.com/gomoob/backbone.hateoas/commit/01610b687ecd95bf852d301c19d32b70501743c2.
